- hosts: all
  handlers:
    - name: daemon reload
      become: yes
      systemd:
        daemon_reload: yes
    - name: restart systemd-resolved
      become: yes
      systemd:
        name: systemd-resolved
        state: restarted
        enabled: yes
    - name: restart openvpn
      become: yes
      systemd:
        name: openvpn-client@vagrant
        state: restarted
        enabled: yes
    - name: restart sshd
      become: yes
      systemd:
        name: sshd
        state: restarted
        enabled: yes
    - name: sleep for openvpn
      wait_for:
        timeout: 5
    - name: direnv allow
      command: direnv allow ~/.envrc

  tasks:
    - name: import os tasks
      import_tasks: provide_os.yml
    - name: import docker tasks
      import_tasks: provide_docker.yml
    - name: import openvpn tasks
      import_tasks: provide_openvpn.yml
    - name: import user tasks
      import_tasks: provide_user.yml
